# Generated by Django 3.2.9 on 2022-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Xmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ymin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Xmax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ymax', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Url', models.URLField()),
                ('Width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Antt', models.ManyToManyField(to='task.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('PID', models.UUIDField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Owner', models.EmailField(max_length=30)),
                ('PostTime', models.DateTimeField(auto_now_add=True)),
                ('IsSubmitted', models.BooleanField()),
                ('IsPassed', models.BooleanField()),
                ('Img', models.ManyToManyField(to='task.Image')),
                ('Submitter', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
