# Generated by Django 3.2.9 on 2022-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='Width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
