# Generated by Django 3.2.9 on 2022-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220102_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='IsPassed',
            field=models.CharField(max_length=25),
        ),
    ]
